In [1]:
import pandas as pd
import numpy as np


In [2]:
df = pd.read_csv('Categories.csv')

In [3]:
df.columns

Index(['id', 'Name'], dtype='object')

In [4]:
df

id                         Name
0   1                         Beer
1   2                         Wine
2   3                      Spirits
3   4  RTDs/High-Strength Premixes
4   5                  Cider/Perry

In [5]:
df1 = pd.read_csv('Channel_Volume.csv')

In [6]:
df1

Location          Industry  Edition Category Subcategory  \
0            1  Alcoholic Drinks     2022     Beer        Beer   
1            1  Alcoholic Drinks     2022     Beer        Beer   
2            1  Alcoholic Drinks     2022     Beer        Beer   
3            1  Alcoholic Drinks     2022     Beer        Beer   
4            1  Alcoholic Drinks     2022     Beer        Beer   
...        ...               ...      ...      ...         ...   
8463         7  Alcoholic Drinks     2022     Beer        Beer   
8464         7  Alcoholic Drinks     2022     Beer        Beer   
8465         7  Alcoholic Drinks     2022     Beer        Beer   
8466         7  Alcoholic Drinks     2022     Beer        Beer   
8467         7  Alcoholic Drinks     2022     Beer        Beer   

      Hierarchy_Level         Data_Type                          Outlet  \
0                   1  Off-trade Volume  Food/drink/tobacco specialists   
1                   1  Off-trade Volume  Food/drink/tobacco specialists   
2                   1  Off-trade Volume  Food/drink/tobacco specialists   
3                   1  Off-trade Volume  Food/drink/tobacco specialists   
4                   1  Off-trade Volume  Food/drink/tobacco specialists   
...               ...               ...                             ...   
8463                1  Off-trade Volume           Store-Based Retailing   
8464                1  Off-trade Volume           Store-Based Retailing   
8465                1  Off-trade Volume           Store-Based Retailing   
8466                1  Off-trade Volume           Store-Based Retailing   
8467                1  Off-trade Volume           Store-Based Retailing   

      Outlet_Hierarchy            Unit  Year_text  \
0                    3  million litres       2007   
1                    3  million litres       2008   
2                    3  million litres       2009   
3                    3  million litres       2010   
4                    3  million litres       2011   
...                ...             ...        ...   
8463                 1  million litres       2017   
8464                 1  million litres       2018   
8465                 1  million litres       2019   
8466                 1  million litres       2020   
8467                 1  million litres       2021   

                        Year_date       Volume  
0        Monday, 31 December 2007  2613,845506  
1     Wednesday, 31 December 2008  2513,025824  
2      Thursday, 31 December 2009  2421,088595  
3        Friday, 31 December 2010  2422,128432  
4      Saturday, 31 December 2011   2439,33622  
...                           ...          ...  
8463     Sunday, 31 December 2017  16514,21084  
8464     Monday, 31 December 2018  16522,15239  
8465    Tuesday, 31 December 2019  16544,60644  
8466   Thursday, 31 December 2020   16626,5149  
8467     Friday, 31 December 2021    16664,638  

[8468 rows x 13 columns]

In [7]:
df2 = pd.read_csv('Company_Share_GBO_unit.csv', sep=';')

In [8]:
df2

Location          Industry  Subcategory_ID  Hierarchy_Level  \
0           NaN               NaN             NaN              NaN   
1           8.0  Alcoholic Drinks            13.0              1.0   
2           NaN               NaN             NaN              NaN   
3           8.0  Alcoholic Drinks            13.0              1.0   
4           NaN               NaN             NaN              NaN   
...         ...               ...             ...              ...   
43331       8.0  Alcoholic Drinks            15.0              1.0   
43332       NaN               NaN             NaN              NaN   
43333       8.0  Alcoholic Drinks            15.0              1.0   
43334       NaN               NaN             NaN              NaN   
43335       8.0  Alcoholic Drinks            15.0              1.0   

          Data_Type       Global_Brand_Owner            Unit  Year_text  \
0               NaN                      NaN             NaN        NaN   
1      Total Volume  Anheuser-Busch InBev NV  million litres     2016.0   
2               NaN                      NaN             NaN        NaN   
3      Total Volume              Heineken NV  million litres     2016.0   
4               NaN                      NaN             NaN        NaN   
...             ...                      ...             ...        ...   
43331  Total Volume        Rosspirtprom FGUP      000 litres     2016.0   
43332           NaN                      NaN             NaN        NaN   
43333  Total Volume            Private Label      000 litres     2016.0   
43334           NaN                      NaN             NaN        NaN   
43335  Total Volume                   Others      000 litres     2016.0   

                   Year_date  Year_minus_2016       Volume  
0                        NaN              NaN          NaN  
1                   31-12-16              4.0  35506,37732  
2                        NaN              NaN          NaN  
3      Saturday, 31 Dec 2016              4.0   18482,5958  
4                        NaN              NaN          NaN  
...                      ...              ...          ...  
43331             31 12 2016              4.0  3,708013795  
43332                    NaN              NaN          NaN  
43333               31-12-16              4.0  307,7663666  
43334                    NaN              NaN          NaN  
43335              31-Dec-16              4.0  8263,549123  

[43336 rows x 11 columns]

In [9]:
df2.columns

Index(['Location', 'Industry', 'Subcategory_ID', 'Hierarchy_Level',
       'Data_Type', 'Global_Brand_Owner', 'Unit', 'Year_text', 'Year_date',
       'Year_minus_2016', 'Volume'],
      dtype='object')

In [10]:
df2.isnull().sum()

Location              21668
Industry              21668
Subcategory_ID        21668
Hierarchy_Level       21668
Data_Type             21668
Global_Brand_Owner    21668
Unit                  21668
Year_text             21668
Year_date             21668
Year_minus_2016       21668
Volume                21668
dtype: int64

In [11]:
df2 = df2.dropna(axis = 0, how = 'all')

In [12]:
df2

Location          Industry  Subcategory_ID  Hierarchy_Level  \
1           8.0  Alcoholic Drinks            13.0              1.0   
3           8.0  Alcoholic Drinks            13.0              1.0   
5           8.0  Alcoholic Drinks            13.0              1.0   
7           8.0  Alcoholic Drinks            13.0              1.0   
9           8.0  Alcoholic Drinks            13.0              1.0   
...         ...               ...             ...              ...   
43327       8.0  Alcoholic Drinks            15.0              1.0   
43329       8.0  Alcoholic Drinks            15.0              1.0   
43331       8.0  Alcoholic Drinks            15.0              1.0   
43333       8.0  Alcoholic Drinks            15.0              1.0   
43335       8.0  Alcoholic Drinks            15.0              1.0   

          Data_Type                         Global_Brand_Owner  \
1      Total Volume                    Anheuser-Busch InBev NV   
3      Total Volume                                Heineken NV   
5      Total Volume                              Carlsberg A/S   
7      Total Volume                          Dragonyte Brewery   
9      Total Volume                    Tsingtao Brewery Co Ltd   
...             ...                                        ...   
43327  Total Volume  Central European Distribution Corp (CEDC)   
43329  Total Volume           Hubei Zhijiang Distillery Co Ltd   
43331  Total Volume                          Rosspirtprom FGUP   
43333  Total Volume                              Private Label   
43335  Total Volume                                     Others   

                 Unit  Year_text              Year_date  Year_minus_2016  \
1      million litres     2016.0               31-12-16              4.0   
3      million litres     2016.0  Saturday, 31 Dec 2016              4.0   
5      million litres     2016.0               31-12-16              4.0   
7      million litres     2016.0              31-Dec-16              4.0   
9      million litres     2016.0             31 12 2016              4.0   
...               ...        ...                    ...              ...   
43327      000 litres     2016.0  Saturday, 31 Dec 2016              4.0   
43329      000 litres     2016.0             31 12 2016              4.0   
43331      000 litres     2016.0             31 12 2016              4.0   
43333      000 litres     2016.0               31-12-16              4.0   
43335      000 litres     2016.0              31-Dec-16              4.0   

            Volume  
1      35506,37732  
3       18482,5958  
5      11121,69868  
7       6252,38259  
9      7834,494901  
...            ...  
43327  223,0247261  
43329  78,55588126  
43331  3,708013795  
43333  307,7663666  
43335  8263,549123  

[21668 rows x 11 columns]

In [13]:
df2.columns

Index(['Location', 'Industry', 'Subcategory_ID', 'Hierarchy_Level',
       'Data_Type', 'Global_Brand_Owner', 'Unit', 'Year_text', 'Year_date',
       'Year_minus_2016', 'Volume'],
      dtype='object')

In [14]:
df2['Location'].unique()

array([8., 7., 3., 1., 6., 4., 2., 5.])

In [15]:
df2.loc[df2['Location'] == 6.0]

Location          Industry  Subcategory_ID  Hierarchy_Level  \
18563       6.0  Alcoholic Drinks             9.0              2.0   
18565       6.0  Alcoholic Drinks             9.0              2.0   
18567       6.0  Alcoholic Drinks             9.0              2.0   
18569       6.0  Alcoholic Drinks             9.0              2.0   
18571       6.0  Alcoholic Drinks             9.0              2.0   
...         ...               ...             ...              ...   
41743       6.0  Alcoholic Drinks            15.0              1.0   
41745       6.0  Alcoholic Drinks            15.0              1.0   
41747       6.0  Alcoholic Drinks            15.0              1.0   
41749       6.0  Alcoholic Drinks            15.0              1.0   
41751       6.0  Alcoholic Drinks            15.0              1.0   

          Data_Type Global_Brand_Owner            Unit  Year_text  \
18563  Total Volume  Dragonyte Brewery  million litres     2016.0   
18565  Total Volume  Dragonyte Brewery  million litres     2017.0   
18567  Total Volume  Dragonyte Brewery  million litres     2018.0   
18569  Total Volume  Dragonyte Brewery  million litres     2019.0   
18571  Total Volume  Dragonyte Brewery  million litres     2020.0   
...             ...                ...             ...        ...   
41743  Total Volume             Others      000 litres     2017.0   
41745  Total Volume             Others      000 litres     2018.0   
41747  Total Volume             Others      000 litres     2019.0   
41749  Total Volume             Others      000 litres     2020.0   
41751  Total Volume             Others      000 litres     2021.0   

                   Year_date  Year_minus_2016       Volume  
18563              31-Dec-16              4.0  295,2988078  
18565  Sun, 31 December 2017              5.0  327,8219829  
18567             31 12 2018              6.0  327,0270668  
18569               31-12-19              7.0  341,2825967  
18571             31 12 2020              8.0  515,1909418  
...                      ...              ...          ...  
41743               31-12-17              5.0  271,5326695  
41745              31-Dec-18              6.0  269,4842455  
41747              31-Dec-19              7.0  273,4744613  
41749  Thursday, 31 Dec 2020              8.0   274,640693  
41751              31-Dec-21              9.0  278,9949661  

[1452 rows x 11 columns]

In [16]:
df2['Industry'].unique()

array(['Alcoholic Drinks'], dtype=object)

In [17]:
df2.loc[df2['Industry'] == 'Alcoholic Drinks']

Location          Industry  Subcategory_ID  Hierarchy_Level  \
1           8.0  Alcoholic Drinks            13.0              1.0   
3           8.0  Alcoholic Drinks            13.0              1.0   
5           8.0  Alcoholic Drinks            13.0              1.0   
7           8.0  Alcoholic Drinks            13.0              1.0   
9           8.0  Alcoholic Drinks            13.0              1.0   
...         ...               ...             ...              ...   
43327       8.0  Alcoholic Drinks            15.0              1.0   
43329       8.0  Alcoholic Drinks            15.0              1.0   
43331       8.0  Alcoholic Drinks            15.0              1.0   
43333       8.0  Alcoholic Drinks            15.0              1.0   
43335       8.0  Alcoholic Drinks            15.0              1.0   

          Data_Type                         Global_Brand_Owner  \
1      Total Volume                    Anheuser-Busch InBev NV   
3      Total Volume                                Heineken NV   
5      Total Volume                              Carlsberg A/S   
7      Total Volume                          Dragonyte Brewery   
9      Total Volume                    Tsingtao Brewery Co Ltd   
...             ...                                        ...   
43327  Total Volume  Central European Distribution Corp (CEDC)   
43329  Total Volume           Hubei Zhijiang Distillery Co Ltd   
43331  Total Volume                          Rosspirtprom FGUP   
43333  Total Volume                              Private Label   
43335  Total Volume                                     Others   

                 Unit  Year_text              Year_date  Year_minus_2016  \
1      million litres     2016.0               31-12-16              4.0   
3      million litres     2016.0  Saturday, 31 Dec 2016              4.0   
5      million litres     2016.0               31-12-16              4.0   
7      million litres     2016.0              31-Dec-16              4.0   
9      million litres     2016.0             31 12 2016              4.0   
...               ...        ...                    ...              ...   
43327      000 litres     2016.0  Saturday, 31 Dec 2016              4.0   
43329      000 litres     2016.0             31 12 2016              4.0   
43331      000 litres     2016.0             31 12 2016              4.0   
43333      000 litres     2016.0               31-12-16              4.0   
43335      000 litres     2016.0              31-Dec-16              4.0   

            Volume  
1      35506,37732  
3       18482,5958  
5      11121,69868  
7       6252,38259  
9      7834,494901  
...            ...  
43327  223,0247261  
43329  78,55588126  
43331  3,708013795  
43333  307,7663666  
43335  8263,549123  

[21668 rows x 11 columns]

In [18]:
df2['Subcategory_ID'].unique()

array([13.,  8.,  4.,  9., 12., 10., 11.,  7.,  3.,  2.,  6.,  5.,  1.,
       17., 16., 14., 15.])

In [19]:
df2.loc[df2['Subcategory_ID'] == 1.0]

Location          Industry  Subcategory_ID  Hierarchy_Level  \
5953        8.0  Alcoholic Drinks             1.0              3.0   
5955        8.0  Alcoholic Drinks             1.0              3.0   
5957        8.0  Alcoholic Drinks             1.0              3.0   
5959        8.0  Alcoholic Drinks             1.0              3.0   
5961        8.0  Alcoholic Drinks             1.0              3.0   
...         ...               ...             ...              ...   
24785       5.0  Alcoholic Drinks             1.0              3.0   
24787       5.0  Alcoholic Drinks             1.0              3.0   
24789       5.0  Alcoholic Drinks             1.0              3.0   
24791       5.0  Alcoholic Drinks             1.0              3.0   
24793       5.0  Alcoholic Drinks             1.0              3.0   

          Data_Type       Global_Brand_Owner            Unit  Year_text  \
5953   Total Volume  Anheuser-Busch InBev NV  million litres     2016.0   
5955   Total Volume  Anheuser-Busch InBev NV  million litres     2017.0   
5957   Total Volume  Anheuser-Busch InBev NV  million litres     2018.0   
5959   Total Volume  Anheuser-Busch InBev NV  million litres     2019.0   
5961   Total Volume  Anheuser-Busch InBev NV  million litres     2020.0   
...             ...                      ...             ...        ...   
24785  Total Volume                   Others  million litres     2017.0   
24787  Total Volume                   Others  million litres     2018.0   
24789  Total Volume                   Others  million litres     2019.0   
24791  Total Volume                   Others  million litres     2020.0   
24793  Total Volume                   Others  million litres     2021.0   

                   Year_date  Year_minus_2016       Volume  
5953                31-12-16              4.0  442,7930849  
5955   Sun, 31 December 2017              5.0  444,8841859  
5957                31-12-18              6.0  452,3452287  
5959              31 12 2019              7.0  454,8540911  
5961               31-Dec-20              8.0  488,6525196  
...                      ...              ...          ...  
24785               31-12-17              5.0  6,000130364  
24787               31-12-18              6.0  5,750886897  
24789   Tuesday, 31 Dec 2019              7.0  6,077533911  
24791             31 12 2020              8.0  6,674982102  
24793               31-12-21              9.0  7,170049506  

[1059 rows x 11 columns]

In [20]:
df2.columns

Index(['Location', 'Industry', 'Subcategory_ID', 'Hierarchy_Level',
       'Data_Type', 'Global_Brand_Owner', 'Unit', 'Year_text', 'Year_date',
       'Year_minus_2016', 'Volume'],
      dtype='object')

In [21]:
df2['Hierarchy_Level'].unique()

array([1., 2., 3., 4.])

In [22]:
df2['Data_Type'].unique()

array(['Total Volume'], dtype=object)

In [23]:
df2['Global_Brand_Owner'].unique()

array(['Anheuser-Busch InBev NV', 'Heineken NV', 'Carlsberg A/S', ...,
       'Eliza Spring LLC', 'Forty Creek Distillery Ltd',
       'White Rock Distilleries Inc'], dtype=object)

In [24]:
df2['Unit'].unique()

array(['million litres', '000 litres'], dtype=object)

In [25]:
df2.loc[df2['Unit'] == '000 litres']

Location          Industry  Subcategory_ID  Hierarchy_Level  \
24915       1.0  Alcoholic Drinks            17.0              1.0   
24917       1.0  Alcoholic Drinks            17.0              1.0   
24919       1.0  Alcoholic Drinks            17.0              1.0   
24921       1.0  Alcoholic Drinks            17.0              1.0   
24923       1.0  Alcoholic Drinks            17.0              1.0   
...         ...               ...             ...              ...   
43327       8.0  Alcoholic Drinks            15.0              1.0   
43329       8.0  Alcoholic Drinks            15.0              1.0   
43331       8.0  Alcoholic Drinks            15.0              1.0   
43333       8.0  Alcoholic Drinks            15.0              1.0   
43335       8.0  Alcoholic Drinks            15.0              1.0   

          Data_Type                         Global_Brand_Owner        Unit  \
24915  Total Volume                                Heineken NV  000 litres   
24917  Total Volume                                Heineken NV  000 litres   
24919  Total Volume                                Heineken NV  000 litres   
24921  Total Volume                                Heineken NV  000 litres   
24923  Total Volume                                Heineken NV  000 litres   
...             ...                                        ...         ...   
43327  Total Volume  Central European Distribution Corp (CEDC)  000 litres   
43329  Total Volume           Hubei Zhijiang Distillery Co Ltd  000 litres   
43331  Total Volume                          Rosspirtprom FGUP  000 litres   
43333  Total Volume                              Private Label  000 litres   
43335  Total Volume                                     Others  000 litres   

       Year_text              Year_date  Year_minus_2016       Volume  
24915     2016.0             31 12 2016              4.0  0,545677495  
24917     2017.0              31-Dec-17              5.0   0,55121634  
24919     2018.0              31-Dec-18              6.0  0,606443429  
24921     2019.0              31-Dec-19              7.0  2,352877598  
24923     2020.0               31-12-20              8.0  3,123034674  
...          ...                    ...              ...          ...  
43327     2016.0  Saturday, 31 Dec 2016              4.0  223,0247261  
43329     2016.0             31 12 2016              4.0  78,55588126  
43331     2016.0             31 12 2016              4.0  3,708013795  
43333     2016.0               31-12-16              4.0  307,7663666  
43335     2016.0              31-Dec-16              4.0  8263,549123  

[6338 rows x 11 columns]

In [26]:
df2.columns

Index(['Location', 'Industry', 'Subcategory_ID', 'Hierarchy_Level',
       'Data_Type', 'Global_Brand_Owner', 'Unit', 'Year_text', 'Year_date',
       'Year_minus_2016', 'Volume'],
      dtype='object')

In [27]:
df2

Location          Industry  Subcategory_ID  Hierarchy_Level  \
1           8.0  Alcoholic Drinks            13.0              1.0   
3           8.0  Alcoholic Drinks            13.0              1.0   
5           8.0  Alcoholic Drinks            13.0              1.0   
7           8.0  Alcoholic Drinks            13.0              1.0   
9           8.0  Alcoholic Drinks            13.0              1.0   
...         ...               ...             ...              ...   
43327       8.0  Alcoholic Drinks            15.0              1.0   
43329       8.0  Alcoholic Drinks            15.0              1.0   
43331       8.0  Alcoholic Drinks            15.0              1.0   
43333       8.0  Alcoholic Drinks            15.0              1.0   
43335       8.0  Alcoholic Drinks            15.0              1.0   

          Data_Type                         Global_Brand_Owner  \
1      Total Volume                    Anheuser-Busch InBev NV   
3      Total Volume                                Heineken NV   
5      Total Volume                              Carlsberg A/S   
7      Total Volume                          Dragonyte Brewery   
9      Total Volume                    Tsingtao Brewery Co Ltd   
...             ...                                        ...   
43327  Total Volume  Central European Distribution Corp (CEDC)   
43329  Total Volume           Hubei Zhijiang Distillery Co Ltd   
43331  Total Volume                          Rosspirtprom FGUP   
43333  Total Volume                              Private Label   
43335  Total Volume                                     Others   

                 Unit  Year_text              Year_date  Year_minus_2016  \
1      million litres     2016.0               31-12-16              4.0   
3      million litres     2016.0  Saturday, 31 Dec 2016              4.0   
5      million litres     2016.0               31-12-16              4.0   
7      million litres     2016.0              31-Dec-16              4.0   
9      million litres     2016.0             31 12 2016              4.0   
...               ...        ...                    ...              ...   
43327      000 litres     2016.0  Saturday, 31 Dec 2016              4.0   
43329      000 litres     2016.0             31 12 2016              4.0   
43331      000 litres     2016.0             31 12 2016              4.0   
43333      000 litres     2016.0               31-12-16              4.0   
43335      000 litres     2016.0              31-Dec-16              4.0   

            Volume  
1      35506,37732  
3       18482,5958  
5      11121,69868  
7       6252,38259  
9      7834,494901  
...            ...  
43327  223,0247261  
43329  78,55588126  
43331  3,708013795  
43333  307,7663666  
43335  8263,549123  

[21668 rows x 11 columns]

In [28]:
df2['Year_text'].unique()

array([2016., 2017., 2018., 2019., 2020., 2021.])

In [29]:
df2['Volume'].unique()

array(['35506,37732', '18482,5958', '11121,69868', ..., '3,708013795',
       '307,7663666', '8263,549123'], dtype=object)

In [30]:
df3 = pd.read_csv('Locations.csv', sep=';')

In [31]:
df3

id   0             1  0.1            2  0.2               3  0.3  \
0   Region NaN  Asia Pacific  NaN  Australasia  NaN  Eastern Europe  NaN   
1  Country NaN  Asia Pacific  NaN  Australasia  NaN  Eastern Europe  NaN   

               4  0.4                       5  0.5              6  0.6  \
0  Latin America  NaN  Middle East and Africa  NaN  North America  NaN   
1  Latin America  NaN  Middle East and Africa  NaN  North America  NaN   

                7  0.7      8  0.8  
0  Western Europe  NaN  World  NaN  
1  Western Europe  NaN  World  NaN

In [32]:
df3 = df3.dropna(axis = 1, how = 'all')

In [33]:
df3

id             1            2               3              4  \
0   Region  Asia Pacific  Australasia  Eastern Europe  Latin America   
1  Country  Asia Pacific  Australasia  Eastern Europe  Latin America   

                        5              6               7      8  
0  Middle East and Africa  North America  Western Europe  World  
1  Middle East and Africa  North America  Western Europe  World

In [34]:
df3.index

RangeIndex(start=0, stop=2, step=1)

In [35]:
df3.T

0                       1
id                  Region                 Country
1             Asia Pacific            Asia Pacific
2              Australasia             Australasia
3           Eastern Europe          Eastern Europe
4            Latin America           Latin America
5   Middle East and Africa  Middle East and Africa
6            North America           North America
7           Western Europe          Western Europe
8                    World                   World

In [36]:
df3.reset_index().T

0                       1
index                       0                       1
id                     Region                 Country
1                Asia Pacific            Asia Pacific
2                 Australasia             Australasia
3              Eastern Europe          Eastern Europe
4               Latin America           Latin America
5      Middle East and Africa  Middle East and Africa
6               North America           North America
7              Western Europe          Western Europe
8                       World                   World

In [37]:
df3

id             1            2               3              4  \
0   Region  Asia Pacific  Australasia  Eastern Europe  Latin America   
1  Country  Asia Pacific  Australasia  Eastern Europe  Latin America   

                        5              6               7      8  
0  Middle East and Africa  North America  Western Europe  World  
1  Middle East and Africa  North America  Western Europe  World

In [38]:
df3.T

0                       1
id                  Region                 Country
1             Asia Pacific            Asia Pacific
2              Australasia             Australasia
3           Eastern Europe          Eastern Europe
4            Latin America           Latin America
5   Middle East and Africa  Middle East and Africa
6            North America           North America
7           Western Europe          Western Europe
8                    World                   World

In [39]:
df3.columns

Index(['id', '1', '2', '3', '4', '5', '6', '7', '8'], dtype='object')

In [40]:
df3

id             1            2               3              4  \
0   Region  Asia Pacific  Australasia  Eastern Europe  Latin America   
1  Country  Asia Pacific  Australasia  Eastern Europe  Latin America   

                        5              6               7      8  
0  Middle East and Africa  North America  Western Europe  World  
1  Middle East and Africa  North America  Western Europe  World

In [41]:
df3 = df3.set_index('id').T

In [42]:
df3.columns

Index(['Region', 'Country'], dtype='object', name='id')

In [43]:
df3.columns

Index(['Region', 'Country'], dtype='object', name='id')

In [44]:
df3 = df3.reset_index(drop=True)

In [45]:
df3.reset_index()

id  index                  Region                 Country
0       0            Asia Pacific            Asia Pacific
1       1             Australasia             Australasia
2       2          Eastern Europe          Eastern Europe
3       3           Latin America           Latin America
4       4  Middle East and Africa  Middle East and Africa
5       5           North America           North America
6       6          Western Europe          Western Europe
7       7                   World                   World

In [46]:
df3.columns

Index(['Region', 'Country'], dtype='object', name='id')

In [47]:
df4 = pd.read_csv('Market_Sizes.csv')

In [48]:
df4

Location          Industry  Subcategory  Hierarchy_Level  \
0            1  Alcoholic Drinks            1                3   
1            1  Alcoholic Drinks            1                3   
2            1  Alcoholic Drinks            1                3   
3            1  Alcoholic Drinks            1                3   
4            1  Alcoholic Drinks            1                3   
...        ...               ...          ...              ...   
1216         7  Alcoholic Drinks           17                1   
1217         7  Alcoholic Drinks           17                1   
1218         7  Alcoholic Drinks           17                1   
1219         7  Alcoholic Drinks           17                1   
1220         7  Alcoholic Drinks           17                1   

            Data_Type         Unit  \
0     Total Value RSP  USD million   
1     Total Value RSP  USD million   
2     Total Value RSP  USD million   
3     Total Value RSP  USD million   
4     Total Value RSP  USD million   
...               ...          ...   
1216  Total Value RSP  USD million   
1217  Total Value RSP  USD million   
1218  Total Value RSP  USD million   
1219  Total Value RSP  USD million   
1220  Total Value RSP  USD million   

                                       Current_Constant  \
0     Historic Constant 2021 Prices, Forecast Consta...   
1     Historic Constant 2021 Prices, Forecast Consta...   
2     Historic Constant 2021 Prices, Forecast Consta...   
3     Historic Constant 2021 Prices, Forecast Consta...   
4     Historic Constant 2021 Prices, Forecast Consta...   
...                                                 ...   
1216  Historic Constant 2021 Prices, Forecast Consta...   
1217  Historic Constant 2021 Prices, Forecast Consta...   
1218  Historic Constant 2021 Prices, Forecast Consta...   
1219  Historic Constant 2021 Prices, Forecast Consta...   
1220  Historic Constant 2021 Prices, Forecast Consta...   

                                    Currency_Conversion  Year  Year_date  \
0     Historic Fixed 2021 Exchange Rates, Forecast F...  2016  31-Dec-16   
1     Historic Fixed 2021 Exchange Rates, Forecast F...  2017  31-Dec-17   
2     Historic Fixed 2021 Exchange Rates, Forecast F...  2018  31-Dec-18   
3     Historic Fixed 2021 Exchange Rates, Forecast F...  2019  31-Dec-19   
4     Historic Fixed 2021 Exchange Rates, Forecast F...  2020  31-Dec-20   
...                                                 ...   ...        ...   
1216  Historic Fixed 2021 Exchange Rates, Forecast F...  2022  31-Dec-22   
1217  Historic Fixed 2021 Exchange Rates, Forecast F...  2023  31-Dec-23   
1218  Historic Fixed 2021 Exchange Rates, Forecast F...  2024  31-Dec-24   
1219  Historic Fixed 2021 Exchange Rates, Forecast F...  2025  31-Dec-25   
1220  Historic Fixed 2021 Exchange Rates, Forecast F...  2026  31-Dec-26   

          RSP  Volume  Year_minus_2016  Year_minus_2022  Edition  
0     301.000  27.000                4               -2     2022  
1     318.000  28.000                5               -1     2022  
2     458.000  40.000                6                0     2022  
3     612.000  51.000                7                1     2022  
4     774.000  62.000                8                2     2022  
...       ...     ...              ...              ...      ...  
1216    6.545   1.204               10                4     2022  
1217    6.628   1.214               11                5     2022  
1218    6.708   1.227               12                6     2022  
1219    6.793   1.240               13                7     2022  
1220    6.892   1.256               14                8     2022  

[1221 rows x 15 columns]

In [49]:
df4.columns

Index(['Location', 'Industry', 'Subcategory', 'Hierarchy_Level', 'Data_Type',
       'Unit', 'Current_Constant', 'Currency_Conversion', 'Year', 'Year_date',
       'RSP', 'Volume', 'Year_minus_2016', 'Year_minus_2022', 'Edition'],
      dtype='object')

In [50]:
df4['Location'].unique()

array([1, 2, 3, 4, 5, 6, 7])

In [51]:
df4['Industry'].unique()

array(['Alcoholic Drinks'], dtype=object)

In [52]:
df4['Subcategory'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [53]:
df4['Hierarchy_Level'].unique()

array([3, 2, 4, 1])

In [54]:
df4['Data_Type'].unique()

array(['Total Value RSP'], dtype=object)

In [55]:
df4['Unit'].unique()

array(['USD million'], dtype=object)

In [56]:
df4['Current_Constant'].unique()

array(['Historic Constant 2021 Prices, Forecast Constant 2021 Prices'],
      dtype=object)

In [57]:
df4.columns

Index(['Location', 'Industry', 'Subcategory', 'Hierarchy_Level', 'Data_Type',
       'Unit', 'Current_Constant', 'Currency_Conversion', 'Year', 'Year_date',
       'RSP', 'Volume', 'Year_minus_2016', 'Year_minus_2022', 'Edition'],
      dtype='object')

In [58]:
df4['Currency_Conversion'].unique()

array(['Historic Fixed 2021 Exchange Rates, Forecast Fixed 2021 Exchange Rates'],
      dtype=object)

In [59]:
df4['Year'].unique()

array([2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026])

In [60]:
df4['Year_date'].unique()

array(['31-Dec-16', '31-Dec-17', '31-Dec-18', '31-Dec-19', '31-Dec-20',
       '31-Dec-21', '31-Dec-22', '31-Dec-23', '31-Dec-24', '31-Dec-25',
       '31-Dec-26', '31-Dec-87', '31-Dec-66', '31-Dec-76'], dtype=object)

In [61]:
df4['RSP'].unique()

array([301.   , 318.   , 458.   , ...,   6.708,   6.793,   6.892])

In [62]:
df4['Volume'].nunique()

995

In [63]:
df4.columns

Index(['Location', 'Industry', 'Subcategory', 'Hierarchy_Level', 'Data_Type',
       'Unit', 'Current_Constant', 'Currency_Conversion', 'Year', 'Year_date',
       'RSP', 'Volume', 'Year_minus_2016', 'Year_minus_2022', 'Edition'],
      dtype='object')

In [64]:
df4['Year_minus_2016'].unique()

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [65]:
df4['Year_minus_2022'].unique()

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [66]:
df4['Edition'].unique()

array([2022])

In [67]:
df5= pd.read_csv('Subcategories.csv')

In [68]:
df5

id  Category                         Name
0    1         1                          Ale
1    2         1  Weissbier/Weizen/Wheat Beer
2    3         1        Flavoured/Mixed Lager
3    4         1               Standard Lager
4    5         1                      Sorghum
5    6         1                        Stout
6    7         1           Non Alcoholic Beer
7    8         1                        Lager
8    9         1                    Dark Beer
9   10         1                Premium Lager
10  11         1             Mid-Priced Lager
11  12         1                Economy Lager
12  13         1                         Beer
13  14         2                         Wine
14  15         3                      Spirits
15  16         4  RTDs/High-Strength Premixes
16  17         5                  Cider/Perry

In [69]:
df5.columns

Index(['id', 'Category', 'Name'], dtype='object')

In [70]:
df5 = df5.reset_index(drop=True)

In [71]:
df5.columns

Index(['id', 'Category', 'Name'], dtype='object')

In [72]:
df5.index

RangeIndex(start=0, stop=17, step=1)

In [73]:
df3 = pd.read_csv('Locations.csv', sep=';',index_col=False)

In [74]:
df3

id   0             1  0.1            2  0.2               3  0.3  \
0   Region NaN  Asia Pacific  NaN  Australasia  NaN  Eastern Europe  NaN   
1  Country NaN  Asia Pacific  NaN  Australasia  NaN  Eastern Europe  NaN   

               4  0.4                       5  0.5              6  0.6  \
0  Latin America  NaN  Middle East and Africa  NaN  North America  NaN   
1  Latin America  NaN  Middle East and Africa  NaN  North America  NaN   

                7  0.7      8  0.8  
0  Western Europe  NaN  World  NaN  
1  Western Europe  NaN  World  NaN

In [75]:
df3.set_index('id')

0             1  0.1            2  0.2               3  0.3  \
id                                                                      
Region  NaN  Asia Pacific  NaN  Australasia  NaN  Eastern Europe  NaN   
Country NaN  Asia Pacific  NaN  Australasia  NaN  Eastern Europe  NaN   

                     4  0.4                       5  0.5              6  0.6  \
id                                                                             
Region   Latin America  NaN  Middle East and Africa  NaN  North America  NaN   
Country  Latin America  NaN  Middle East and Africa  NaN  North America  NaN   

                      7  0.7      8  0.8  
id                                        
Region   Western Europe  NaN  World  NaN  
Country  Western Europe  NaN  World  NaN

In [76]:
df3 = df3.T

In [77]:
df3 = df3.T

In [78]:
df3 = df3.dropna(axis = 1, how = 'all')

In [79]:
df3

id             1            2               3              4  \
0   Region  Asia Pacific  Australasia  Eastern Europe  Latin America   
1  Country  Asia Pacific  Australasia  Eastern Europe  Latin America   

                        5              6               7      8  
0  Middle East and Africa  North America  Western Europe  World  
1  Middle East and Africa  North America  Western Europe  World

In [80]:
df3.set_index('id')

1            2               3              4  \
id                                                                  
Region   Asia Pacific  Australasia  Eastern Europe  Latin America   
Country  Asia Pacific  Australasia  Eastern Europe  Latin America   

                              5              6               7      8  
id                                                                     
Region   Middle East and Africa  North America  Western Europe  World  
Country  Middle East and Africa  North America  Western Europe  World

In [81]:
df3

id             1            2               3              4  \
0   Region  Asia Pacific  Australasia  Eastern Europe  Latin America   
1  Country  Asia Pacific  Australasia  Eastern Europe  Latin America   

                        5              6               7      8  
0  Middle East and Africa  North America  Western Europe  World  
1  Middle East and Africa  North America  Western Europe  World

In [82]:
df3.set_index('id')

1            2               3              4  \
id                                                                  
Region   Asia Pacific  Australasia  Eastern Europe  Latin America   
Country  Asia Pacific  Australasia  Eastern Europe  Latin America   

                              5              6               7      8  
id                                                                     
Region   Middle East and Africa  North America  Western Europe  World  
Country  Middle East and Africa  North America  Western Europe  World

In [83]:
df3 = df3.set_index('id')

In [84]:
df3

1            2               3              4  \
id                                                                  
Region   Asia Pacific  Australasia  Eastern Europe  Latin America   
Country  Asia Pacific  Australasia  Eastern Europe  Latin America   

                              5              6               7      8  
id                                                                     
Region   Middle East and Africa  North America  Western Europe  World  
Country  Middle East and Africa  North America  Western Europe  World

In [85]:
df3.T

id                  Region                 Country
1             Asia Pacific            Asia Pacific
2              Australasia             Australasia
3           Eastern Europe          Eastern Europe
4            Latin America           Latin America
5   Middle East and Africa  Middle East and Africa
6            North America           North America
7           Western Europe          Western Europe
8                    World                   World

In [86]:
df3= df3.T

In [87]:
df3

id                  Region                 Country
1             Asia Pacific            Asia Pacific
2              Australasia             Australasia
3           Eastern Europe          Eastern Europe
4            Latin America           Latin America
5   Middle East and Africa  Middle East and Africa
6            North America           North America
7           Western Europe          Western Europe
8                    World                   World

In [88]:
df3.reset_index()

id index                  Region                 Country
0      1            Asia Pacific            Asia Pacific
1      2             Australasia             Australasia
2      3          Eastern Europe          Eastern Europe
3      4           Latin America           Latin America
4      5  Middle East and Africa  Middle East and Africa
5      6           North America           North America
6      7          Western Europe          Western Europe
7      8                   World                   World

In [89]:
df3.columns

Index(['Region', 'Country'], dtype='object', name='id')

In [90]:
df3['Region']

1              Asia Pacific
2               Australasia
3            Eastern Europe
4             Latin America
5    Middle East and Africa
6             North America
7            Western Europe
8                     World
Name: Region, dtype: object

In [91]:
df3.index

Index(['1', '2', '3', '4', '5', '6', '7', '8'], dtype='object')

In [92]:
df3.set_index('id')

KeyError: "None of ['id'] are in the columns"

In [93]:
df3

id                  Region                 Country
1             Asia Pacific            Asia Pacific
2              Australasia             Australasia
3           Eastern Europe          Eastern Europe
4            Latin America           Latin America
5   Middle East and Africa  Middle East and Africa
6            North America           North America
7           Western Europe          Western Europe
8                    World                   World

In [94]:
df1.isnull().sum()

Location            0
Industry            0
Edition             0
Category            4
Subcategory         0
Hierarchy_Level     0
Data_Type           0
Outlet              0
Outlet_Hierarchy    0
Unit                0
Year_text           0
Year_date           0
Volume              0
dtype: int64

In [95]:
df1['Category'].unique()

array(['Beer', 'Cider/Perry', 'RTDs/High-Strength Premixes', 'Spirits',
       'Wine', nan], dtype=object)

In [96]:
filt = df1['Category']== nan
df1[filt]

NameError: name 'nan' is not defined

In [97]:
updated_df1 = df1.drop(df1[df1['Category'].isna()].index)

In [98]:
updated_df1.isnull().sum()

Location            0
Industry            0
Edition             0
Category            0
Subcategory         0
Hierarchy_Level     0
Data_Type           0
Outlet              0
Outlet_Hierarchy    0
Unit                0
Year_text           0
Year_date           0
Volume              0
dtype: int64

In [99]:
df1.loc[df1['Unit']=='million litres','Volume']

0       2613,845506
1       2513,025824
2       2421,088595
3       2422,128432
4        2439,33622
           ...     
8463    16514,21084
8464    16522,15239
8465    16544,60644
8466     16626,5149
8467      16664,638
Name: Volume, Length: 3596, dtype: object

In [100]:
updated_df1.dtypes

Location             int64
Industry            object
Edition              int64
Category            object
Subcategory         object
Hierarchy_Level      int64
Data_Type           object
Outlet              object
Outlet_Hierarchy     int64
Unit                object
Year_text            int64
Year_date           object
Volume              object
dtype: object

In [101]:
updated_df1['Volume'] = updated_df1['Volume'].str.replace(',','.')

In [102]:
updated_df1['Volume']

0       2613.845506
1       2513.025824
2       2421.088595
3       2422.128432
4        2439.33622
           ...     
8463    16514.21084
8464    16522.15239
8465    16544.60644
8466     16626.5149
8467      16664.638
Name: Volume, Length: 8464, dtype: object

In [103]:
updated_df1 = updated_df1.astype({"Volume":"float"})

In [104]:
updated_df1['Volume']

0        2613.845506
1        2513.025824
2        2421.088595
3        2422.128432
4        2439.336220
            ...     
8463    16514.210840
8464    16522.152390
8465    16544.606440
8466    16626.514900
8467    16664.638000
Name: Volume, Length: 8464, dtype: float64

In [105]:
updated_df1.loc[updated_df1['Unit']=='million litres','Volume'] = updated_df1.loc[updated_df1['Unit']=='million litres','Volume'] * 1000

In [106]:
updated_df1.loc[updated_df1['Unit']=='million litres','Volume']

0       2.613846e+06
1       2.513026e+06
2       2.421089e+06
3       2.422128e+06
4       2.439336e+06
            ...     
8463    1.651421e+07
8464    1.652215e+07
8465    1.654461e+07
8466    1.662651e+07
8467    1.666464e+07
Name: Volume, Length: 3594, dtype: float64

In [107]:
updated_df1.loc[updated_df1['Unit']=='million litres','Unit'] = '1000 litres'

In [108]:
updated_df1.loc[updated_df1['Unit']=='1000 litres','Unit']

0       1000 litres
1       1000 litres
2       1000 litres
3       1000 litres
4       1000 litres
           ...     
8463    1000 litres
8464    1000 litres
8465    1000 litres
8466    1000 litres
8467    1000 litres
Name: Unit, Length: 3594, dtype: object

In [109]:
updated_df1['Unit']

0       1000 litres
1       1000 litres
2       1000 litres
3       1000 litres
4       1000 litres
           ...     
8463    1000 litres
8464    1000 litres
8465    1000 litres
8466    1000 litres
8467    1000 litres
Name: Unit, Length: 8464, dtype: object

In [110]:
updated_df1.loc[updated_df1['Unit']=='000 litres','Unit'] = '1000 litres'

In [111]:
updated_df1

Location          Industry  Edition Category Subcategory  \
0            1  Alcoholic Drinks     2022     Beer        Beer   
1            1  Alcoholic Drinks     2022     Beer        Beer   
2            1  Alcoholic Drinks     2022     Beer        Beer   
3            1  Alcoholic Drinks     2022     Beer        Beer   
4            1  Alcoholic Drinks     2022     Beer        Beer   
...        ...               ...      ...      ...         ...   
8463         7  Alcoholic Drinks     2022     Beer        Beer   
8464         7  Alcoholic Drinks     2022     Beer        Beer   
8465         7  Alcoholic Drinks     2022     Beer        Beer   
8466         7  Alcoholic Drinks     2022     Beer        Beer   
8467         7  Alcoholic Drinks     2022     Beer        Beer   

      Hierarchy_Level         Data_Type                          Outlet  \
0                   1  Off-trade Volume  Food/drink/tobacco specialists   
1                   1  Off-trade Volume  Food/drink/tobacco specialists   
2                   1  Off-trade Volume  Food/drink/tobacco specialists   
3                   1  Off-trade Volume  Food/drink/tobacco specialists   
4                   1  Off-trade Volume  Food/drink/tobacco specialists   
...               ...               ...                             ...   
8463                1  Off-trade Volume           Store-Based Retailing   
8464                1  Off-trade Volume           Store-Based Retailing   
8465                1  Off-trade Volume           Store-Based Retailing   
8466                1  Off-trade Volume           Store-Based Retailing   
8467                1  Off-trade Volume           Store-Based Retailing   

      Outlet_Hierarchy         Unit  Year_text                    Year_date  \
0                    3  1000 litres       2007     Monday, 31 December 2007   
1                    3  1000 litres       2008  Wednesday, 31 December 2008   
2                    3  1000 litres       2009   Thursday, 31 December 2009   
3                    3  1000 litres       2010     Friday, 31 December 2010   
4                    3  1000 litres       2011   Saturday, 31 December 2011   
...                ...          ...        ...                          ...   
8463                 1  1000 litres       2017     Sunday, 31 December 2017   
8464                 1  1000 litres       2018     Monday, 31 December 2018   
8465                 1  1000 litres       2019    Tuesday, 31 December 2019   
8466                 1  1000 litres       2020   Thursday, 31 December 2020   
8467                 1  1000 litres       2021     Friday, 31 December 2021   

            Volume  
0     2.613846e+06  
1     2.513026e+06  
2     2.421089e+06  
3     2.422128e+06  
4     2.439336e+06  
...            ...  
8463  1.651421e+07  
8464  1.652215e+07  
8465  1.654461e+07  
8466  1.662651e+07  
8467  1.666464e+07  

[8464 rows x 13 columns]

In [112]:
updated_df1['Unit'].unique()

array(['1000 litres'], dtype=object)

In [113]:
updated_df1.to_csv('Channel Volume1_0.csv')

In [114]:
updated_df1['Year_date'] = updated_df1['Year_date'].str.split(',').str[1]

In [115]:
updated_df1['Year_date'] = updated_df1['Year_date'].str.split(' ').str[1] + '-12-'+ updated_df1['Year_date'].str.split(' ').str[3]

In [116]:
updated_df1['Year_date']

0       31-12-2007
1       31-12-2008
2       31-12-2009
3       31-12-2010
4       31-12-2011
           ...    
8463    31-12-2017
8464    31-12-2018
8465    31-12-2019
8466    31-12-2020
8467    31-12-2021
Name: Year_date, Length: 8464, dtype: object

In [117]:
df4

Location          Industry  Subcategory  Hierarchy_Level  \
0            1  Alcoholic Drinks            1                3   
1            1  Alcoholic Drinks            1                3   
2            1  Alcoholic Drinks            1                3   
3            1  Alcoholic Drinks            1                3   
4            1  Alcoholic Drinks            1                3   
...        ...               ...          ...              ...   
1216         7  Alcoholic Drinks           17                1   
1217         7  Alcoholic Drinks           17                1   
1218         7  Alcoholic Drinks           17                1   
1219         7  Alcoholic Drinks           17                1   
1220         7  Alcoholic Drinks           17                1   

            Data_Type         Unit  \
0     Total Value RSP  USD million   
1     Total Value RSP  USD million   
2     Total Value RSP  USD million   
3     Total Value RSP  USD million   
4     Total Value RSP  USD million   
...               ...          ...   
1216  Total Value RSP  USD million   
1217  Total Value RSP  USD million   
1218  Total Value RSP  USD million   
1219  Total Value RSP  USD million   
1220  Total Value RSP  USD million   

                                       Current_Constant  \
0     Historic Constant 2021 Prices, Forecast Consta...   
1     Historic Constant 2021 Prices, Forecast Consta...   
2     Historic Constant 2021 Prices, Forecast Consta...   
3     Historic Constant 2021 Prices, Forecast Consta...   
4     Historic Constant 2021 Prices, Forecast Consta...   
...                                                 ...   
1216  Historic Constant 2021 Prices, Forecast Consta...   
1217  Historic Constant 2021 Prices, Forecast Consta...   
1218  Historic Constant 2021 Prices, Forecast Consta...   
1219  Historic Constant 2021 Prices, Forecast Consta...   
1220  Historic Constant 2021 Prices, Forecast Consta...   

                                    Currency_Conversion  Year  Year_date  \
0     Historic Fixed 2021 Exchange Rates, Forecast F...  2016  31-Dec-16   
1     Historic Fixed 2021 Exchange Rates, Forecast F...  2017  31-Dec-17   
2     Historic Fixed 2021 Exchange Rates, Forecast F...  2018  31-Dec-18   
3     Historic Fixed 2021 Exchange Rates, Forecast F...  2019  31-Dec-19   
4     Historic Fixed 2021 Exchange Rates, Forecast F...  2020  31-Dec-20   
...                                                 ...   ...        ...   
1216  Historic Fixed 2021 Exchange Rates, Forecast F...  2022  31-Dec-22   
1217  Historic Fixed 2021 Exchange Rates, Forecast F...  2023  31-Dec-23   
1218  Historic Fixed 2021 Exchange Rates, Forecast F...  2024  31-Dec-24   
1219  Historic Fixed 2021 Exchange Rates, Forecast F...  2025  31-Dec-25   
1220  Historic Fixed 2021 Exchange Rates, Forecast F...  2026  31-Dec-26   

          RSP  Volume  Year_minus_2016  Year_minus_2022  Edition  
0     301.000  27.000                4               -2     2022  
1     318.000  28.000                5               -1     2022  
2     458.000  40.000                6                0     2022  
3     612.000  51.000                7                1     2022  
4     774.000  62.000                8                2     2022  
...       ...     ...              ...              ...      ...  
1216    6.545   1.204               10                4     2022  
1217    6.628   1.214               11                5     2022  
1218    6.708   1.227               12                6     2022  
1219    6.793   1.240               13                7     2022  
1220    6.892   1.256               14                8     2022  

[1221 rows x 15 columns]

In [118]:
df4['Subcategory'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [119]:
df4.loc[df4['Subcategory'] == 5,'']

KeyError: ''

In [121]:
df7= pd.read_csv('Company_Share_GBO_unit_clean_V1_3_3.csv')

In [122]:
df7

Unnamed: 0  Location          Industry  Subcategory_ID  \
0               0       8.0  Alcoholic Drinks            13.0   
1               1       8.0  Alcoholic Drinks            13.0   
2               2       8.0  Alcoholic Drinks            13.0   
3               3       8.0  Alcoholic Drinks            13.0   
4               4       8.0  Alcoholic Drinks            13.0   
...           ...       ...               ...             ...   
21663       21663       8.0  Alcoholic Drinks            15.0   
21664       21664       8.0  Alcoholic Drinks            15.0   
21665       21665       8.0  Alcoholic Drinks            15.0   
21666       21666       8.0  Alcoholic Drinks            15.0   
21667       21667       8.0  Alcoholic Drinks            15.0   

       Hierarchy_Level     Data_Type                       Global_Brand_Owner  \
0                  1.0  Total Volume                   AnheuserBusch InBev NV   
1                  1.0  Total Volume                              Heineken NV   
2                  1.0  Total Volume                             Carlsberg AS   
3                  1.0  Total Volume                        Dragonyte Brewery   
4                  1.0  Total Volume                  Tsingtao Brewery Co Ltd   
...                ...           ...                                      ...   
21663              1.0  Total Volume  Central European Distribution Corp CEDC   
21664              1.0  Total Volume         Hubei Zhijiang Distillery Co Ltd   
21665              1.0  Total Volume                        Rosspirtprom FGUP   
21666              1.0  Total Volume                            Private Label   
21667              1.0  Total Volume                                   Others   

                 Unit  Year_text Year_date  Year_minus_2016       Volume  
0      million litres     2016.0  31-12-16              4.0  35506,37732  
1      million litres     2016.0  31-12-16              4.0   18482,5958  
2      million litres     2016.0  31-12-16              4.0  11121,69868  
3      million litres     2016.0  31-12-16              4.0   6252,38259  
4      million litres     2016.0  31-12-16              4.0  7834,494901  
...               ...        ...       ...              ...          ...  
21663      000 litres     2016.0  31-12-16              4.0  223,0247261  
21664      000 litres     2016.0  31-12-16              4.0  78,55588126  
21665      000 litres     2016.0  31-12-16              4.0  3,708013795  
21666      000 litres     2016.0  31-12-16              4.0  307,7663666  
21667      000 litres     2016.0  31-12-16              4.0  8263,549123  

[21668 rows x 12 columns]

In [123]:
df7['Volume'] = df7['Volume'].str.replace(',','.')

In [124]:
df7 = df7.astype({"Volume":"float"})

In [125]:
df7.dtypes

Unnamed: 0              int64
Location              float64
Industry               object
Subcategory_ID        float64
Hierarchy_Level       float64
Data_Type              object
Global_Brand_Owner     object
Unit                   object
Year_text             float64
Year_date              object
Year_minus_2016       float64
Volume                float64
dtype: object

In [126]:
df7['Unit'].unique()

array(['million litres', '000 litres'], dtype=object)

In [127]:
df7.loc[df7['Unit']=='million litres','Volume'] = df7.loc[df7['Unit']=='million litres','Volume'] * 1000

In [128]:
df7.loc[df7['Unit']=='million litres','Unit'] = '1000 litres'

In [129]:
df7.columns

Index(['Unnamed: 0', 'Location', 'Industry', 'Subcategory_ID',
       'Hierarchy_Level', 'Data_Type', 'Global_Brand_Owner', 'Unit',
       'Year_text', 'Year_date', 'Year_minus_2016', 'Volume'],
      dtype='object')

In [132]:
df7.drop('Unnamed: 0',axis=1,inplace=True)

In [133]:
df7

Location          Industry  Subcategory_ID  Hierarchy_Level  \
0           8.0  Alcoholic Drinks            13.0              1.0   
1           8.0  Alcoholic Drinks            13.0              1.0   
2           8.0  Alcoholic Drinks            13.0              1.0   
3           8.0  Alcoholic Drinks            13.0              1.0   
4           8.0  Alcoholic Drinks            13.0              1.0   
...         ...               ...             ...              ...   
21663       8.0  Alcoholic Drinks            15.0              1.0   
21664       8.0  Alcoholic Drinks            15.0              1.0   
21665       8.0  Alcoholic Drinks            15.0              1.0   
21666       8.0  Alcoholic Drinks            15.0              1.0   
21667       8.0  Alcoholic Drinks            15.0              1.0   

          Data_Type                       Global_Brand_Owner         Unit  \
0      Total Volume                   AnheuserBusch InBev NV  1000 litres   
1      Total Volume                              Heineken NV  1000 litres   
2      Total Volume                             Carlsberg AS  1000 litres   
3      Total Volume                        Dragonyte Brewery  1000 litres   
4      Total Volume                  Tsingtao Brewery Co Ltd  1000 litres   
...             ...                                      ...          ...   
21663  Total Volume  Central European Distribution Corp CEDC   000 litres   
21664  Total Volume         Hubei Zhijiang Distillery Co Ltd   000 litres   
21665  Total Volume                        Rosspirtprom FGUP   000 litres   
21666  Total Volume                            Private Label   000 litres   
21667  Total Volume                                   Others   000 litres   

       Year_text Year_date  Year_minus_2016        Volume  
0         2016.0  31-12-16              4.0  3.550638e+07  
1         2016.0  31-12-16              4.0  1.848260e+07  
2         2016.0  31-12-16              4.0  1.112170e+07  
3         2016.0  31-12-16              4.0  6.252383e+06  
4         2016.0  31-12-16              4.0  7.834495e+06  
...          ...       ...              ...           ...  
21663     2016.0  31-12-16              4.0  2.230247e+02  
21664     2016.0  31-12-16              4.0  7.855588e+01  
21665     2016.0  31-12-16              4.0  3.708014e+00  
21666     2016.0  31-12-16              4.0  3.077664e+02  
21667     2016.0  31-12-16              4.0  8.263549e+03  

[21668 rows x 11 columns]

In [134]:
df7.to_csv('Company_Share_GBO_unit_clean_V1_3_3_1.csv')